name: happy_childhood_ui
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^2.19.4

# Add regular dependencies here.
dependencies:
  dropdown_button2: ^2.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

flutter:
  fonts:
    - family: Balyona
      fonts:
        - asset: fonts/Balyona.ttf
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf